apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kvstore-deployment
  labels:
    app: kvstore
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 1
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
      - name: api
        image: local/kv-server
        imagePullPolicy: Never
        ports:
        - name: kvs-server
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: kvstore-service
spec:
  type: NodePort
  selector:
    app: kvstore
  ports:
  - port: 3000
    targetPort: kvs-server
